name: Tink Foo Workflow
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      # 步骤1 拉取仓库代码
      - uses: actions/checkout@v3
      # 步骤2 给当前服务器安装node
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: push message
        run: npx tsx ./src/bot-push.ts --webhook=${{ secrets.DINGDINGBOT_WEBHOOK }} --secret=${{ secrets.DINGDINGBOT_SECRET }}
